apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  namespace: opr
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app

  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          imagePullPolicy: IfNotPresent
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80