apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  namespace: dev
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: myapp
      type: front-end
  replicas: 3